### PR TITLE
Make myISRData static

### PR DESCRIPTION
**Pull request by MarkRivers**
softGlueZynq fails to compile with gcc 11.2.0 with the following errors:
********************
/usr/bin/g++ -o libsoftGlueZynq.so  -shared -fPIC -Wl,-hlibsoftGlueZynq.so -L/corvette/home/epics/devel/softGlueZynq-2-0-4/lib/linux-x86_64-ub18 -L/corvette/home/epics/devel/asyn-4-43/lib/linux-x86_64-ub18 -L/corvette/home/epics/devel/seq-2-2-5/lib/linux-x86_64-ub18 -L/corvette/usr/local/epics-devel/base-7.0.7/lib/linux-x86_64-ub18 -Wl,-rpath,/corvette/home/epics/devel/softGlueZynq-2-0-4/lib/linux-x86_64-ub18 -Wl,-rpath,/corvette/home/epics/devel/asyn-4-43/lib/linux-x86_64-ub18 -Wl,-rpath,/corvette/home/epics/devel/seq-2-2-5/lib/linux-x86_64-ub18 -Wl,-rpath,/corvette/usr/local/epics-devel/base-7.0.7/lib/linux-x86_64-ub18          -rdynamic -m64          drvZynq.o devAsynSoftGlue.o devA32Zed.o sampleCustomInterruptHandler.o pixelTriggerAsub.o scalerAsub.o pixelTriggerDmaAsub.o histScalerDmaAsub.o MCSAsub.o clockConfigAsub.o readSoftGlueCounter_ISR.o devSGscaler16.o   -lasyn -lseq -lpv -ldbRecStd -ldbCore -lca -lCom   -lpthread   -lreadline -lm -lrt -ldl -lgcc

/usr/bin/ld: pixelTriggerAsub.o:/corvette/home/epics/devel/softGlueZynq-2-0-4/softGlueApp/src/O.linux-x86_64-ub18/../pixelTriggerAsub.c:69: multiple definition of `myISRData'; sampleCustomInterruptHandler.o:/corvette/home/epics/devel/softGlueZynq-2-0-4/softGlueApp/src/O.linux-x86_64-ub18/../sampleCustomInterruptHandler.c:27: first defined here

/usr/bin/ld: MCSAsub.o:/corvette/home/epics/devel/softGlueZynq-2-0-4/softGlueApp/src/O.linux-x86_64-ub18/../MCSAsub.c:61: multiple definition of `myISRData'; sampleCustomInterruptHandler.o:/corvette/home/epics/devel/softGlueZynq-2-0-4/softGlueApp/src/O.linux-x86_64-ub18/../sampleCustomInterruptHandler.c:27: first defined here
collect2: error: ld returned 1 exit status
********************

I think this is probably because the definitions of myISRData at the beginning of each file should be static, not global?

### CODE REVIEW

**Comment by MarkRivers** [comment]
It compiles OK if I declare them static, but I am not sure if this breaks the functionalilty.
